; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
board = esp32dev	;	original --> esp32doit-devkit-v1
platform = espressif32@5.3.0	; was 3.5.0 <-- does NOT support LittleFS
; platform = espressif32@ ^6.0	; Doesn't work! cant remember why
framework = arduino
board_build.filesystem = littlefs
lib_ldf_mode = deep
						; ESP32 38-pin = COM6
upload_port = COM7	; ESP32 30-pin = COM7	; ESP32-WROVER 38-pin = COM8
monitor_port = COM7
monitor_speed = 115200
build_flags =
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
lib_deps =
	esphome/ESPAsyncWebServer-esphome @ ^3.0.0
    esphome/AsyncTCP-esphome @ ^2.0.0
	; https://github.com/kosme/arduinoFFT	; Used in original git code
